---
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: yes

- name: add php apt-key
  ansible.builtin.apt_key: 
    url: "https://packages.sury.org/php/apt.gpg" 
    state: present 

- name: add php apt repository
  ansible.builtin.apt_repository: 
    repo: 'deb https://packages.sury.org/php/ bullseye main' 
    state: present 
    filename: "php{{ php_version }}.list" 
    update_cache: yes

- name: Install  dependencies
  ansible.builtin.apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-common
      - php{{ php_version }}-mcrypt
      - php{{ php_version }}-ldap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-gd
      - php{{ php_version }}-intl
      - php{{ php_version }}-xml
      - php{{ php_version }}-snmp
      - php{{ php_version }}-imap
      - php{{ php_version }}-ps
      - php{{ php_version }}-pspell
      - php{{ php_version }}-zip
      - php{{ php_version }}-mysql
      - php{{ php_version }}-curl
      - php{{ php_version }}-cli
      - php-pear
      - python3-ldap
      - apache2
      - libapache2-mod-php
      - php-ldap

    state: present